#!/bin/bash

# Project Cleanup Script for Bill Sharing Salesforce Application
# This script removes unnecessary metadata files to reduce deployment complexity

echo "🧹 Starting project cleanup..."

# Change to project directory
cd "$(dirname "$0")/.."

# Create a log file for the cleanup
LOG_FILE="cleanup-log-$(date +%Y%m%d-%H%M%S).txt"
echo "Cleanup started at $(date)" > "$LOG_FILE"

# Function to safely remove directory if it exists
remove_dir() {
    if [ -d "$1" ]; then
        echo "Removing directory: $1" | tee -a "$LOG_FILE"
        rm -rf "$1"
    fi
}

# Function to safely remove file if it exists
remove_file() {
    if [ -f "$1" ]; then
        echo "Removing file: $1" | tee -a "$LOG_FILE"
        rm -f "$1"
    fi
}

echo "📊 Current project size before cleanup:"
du -sh force-app/main/default

echo ""
echo "🗑️  Removing unnecessary metadata directories..."

# Remove unnecessary application metadata
remove_dir "force-app/main/default/applications"
remove_dir "force-app/main/default/appMenus"
remove_dir "force-app/main/default/appointmentSchedulingPolicies"
remove_dir "force-app/main/default/assignmentRules"
remove_dir "force-app/main/default/autoResponseRules"
remove_dir "force-app/main/default/cleanDataServices"
remove_dir "force-app/main/default/communities"
remove_dir "force-app/main/default/contentassets"
remove_dir "force-app/main/default/dashboards"
remove_dir "force-app/main/default/digitalExperiences"
remove_dir "force-app/main/default/duplicateRules"
remove_dir "force-app/main/default/email"
remove_dir "force-app/main/default/entitlementProcesses"
remove_dir "force-app/main/default/escalationRules"
remove_dir "force-app/main/default/flexipages"
remove_dir "force-app/main/default/homePageLayouts"
remove_dir "force-app/main/default/iframeWhiteListUrlSettings"
remove_dir "force-app/main/default/layouts"
remove_dir "force-app/main/default/lwc"
remove_dir "force-app/main/default/managedContentTypes"
remove_dir "force-app/main/default/matchingRules"
remove_dir "force-app/main/default/milestoneTypes"
remove_dir "force-app/main/default/notificationTypeConfig"
remove_dir "force-app/main/default/notificationtypes"
remove_dir "force-app/main/default/objects/AccountCleanInfo"
remove_dir "force-app/main/default/objects/AccountContactRole"
remove_dir "force-app/main/default/objects/ActivationTarget"
remove_dir "force-app/main/default/objects/ActivationTargetPlatform"
remove_dir "force-app/main/default/objects/Activity"
remove_dir "force-app/main/default/objects/ActvTgtPlatformFieldValue"
remove_dir "force-app/main/default/objects/Address"
remove_dir "force-app/main/default/objects/AgentWork"
remove_dir "force-app/main/default/objects/AiGroundingFileRef"
remove_dir "force-app/main/default/objects/AiGroundingSourceStage"
remove_dir "force-app/main/default/objects/AiGroundingWebRef"
remove_dir "force-app/main/default/objects/AiJobRun"
remove_dir "force-app/main/default/objects/AiJobRunItem"
remove_dir "force-app/main/default/objects/AlternativePaymentMethod"
remove_dir "force-app/main/default/objects/AnalyticsUserAttrFuncTkn"
remove_dir "force-app/main/default/objects/AppointmentCategory"
remove_dir "force-app/main/default/objects/AppointmentInvitation"
remove_dir "force-app/main/default/objects/AppointmentInvitee"
remove_dir "force-app/main/default/objects/AppointmentScheduleLog"
remove_dir "force-app/main/default/objects/AppointmentTopicTimeSlot"
remove_dir "force-app/main/default/objects/ApprovalSubmission"
remove_dir "force-app/main/default/objects/ApprovalSubmissionDetail"
remove_dir "force-app/main/default/objects/ApprovalWorkItem"
remove_dir "force-app/main/default/objects/Asset"
remove_dir "force-app/main/default/objects/AssetAction"
remove_dir "force-app/main/default/objects/AssetActionSource"
remove_dir "force-app/main/default/objects/AssetRelationship"
remove_dir "force-app/main/default/objects/AssetStatePeriod"
remove_dir "force-app/main/default/objects/AssignedResource"
remove_dir "force-app/main/default/objects/AssistantProgress"
remove_dir "force-app/main/default/objects/AssociatedLocation"
remove_dir "force-app/main/default/objects/AuthorizationForm"
remove_dir "force-app/main/default/objects/AuthorizationFormConsent"
remove_dir "force-app/main/default/objects/AuthorizationFormDataUse"
remove_dir "force-app/main/default/objects/AuthorizationFormText"
remove_dir "force-app/main/default/objects/BusinessBrand"
remove_dir "force-app/main/default/objects/BuyerGroup"
remove_dir "force-app/main/default/objects/Campaign"
remove_dir "force-app/main/default/objects/CampaignMember"
remove_dir "force-app/main/default/objects/CardPaymentMethod"
remove_dir "force-app/main/default/objects/CartCheckoutSession"
remove_dir "force-app/main/default/objects/CartDeliveryGroup"
remove_dir "force-app/main/default/objects/CartDeliveryGroupMethod"
remove_dir "force-app/main/default/objects/CartItem"
remove_dir "force-app/main/default/objects/CartItemPriceAdjustment"
remove_dir "force-app/main/default/objects/CartRelatedItem"
remove_dir "force-app/main/default/objects/CartTax"
remove_dir "force-app/main/default/objects/CartValidationOutput"
remove_dir "force-app/main/default/objects/Case"
remove_dir "force-app/main/default/objects/CaseContactRole"
remove_dir "force-app/main/default/objects/CaseMilestone"
remove_dir "force-app/main/default/objects/CaseRelatedIssue"
remove_dir "force-app/main/default/objects/ChangeRequest"
remove_dir "force-app/main/default/objects/ChangeRequestRelatedIssue"
remove_dir "force-app/main/default/objects/ChangeRequestRelatedItem"
remove_dir "force-app/main/default/objects/ChatterActivity"
remove_dir "force-app/main/default/objects/CollaborationGroup"
remove_dir "force-app/main/default/objects/CollaborationGroupMember"
remove_dir "force-app/main/default/objects/CommSubscription"
remove_dir "force-app/main/default/objects/CommSubscriptionChannelType"
remove_dir "force-app/main/default/objects/CommSubscriptionConsent"
remove_dir "force-app/main/default/objects/CommSubscriptionTiming"
remove_dir "force-app/main/default/objects/ConsumptionRate"
remove_dir "force-app/main/default/objects/ConsumptionSchedule"
remove_dir "force-app/main/default/objects/ContactCleanInfo"
remove_dir "force-app/main/default/objects/ContactPointAddress"
remove_dir "force-app/main/default/objects/ContactPointConsent"
remove_dir "force-app/main/default/objects/ContactPointEmail"
remove_dir "force-app/main/default/objects/ContactPointPhone"
remove_dir "force-app/main/default/objects/ContactPointTypeConsent"
remove_dir "force-app/main/default/objects/ContactRequest"
remove_dir "force-app/main/default/objects/ContentVersion"
remove_dir "force-app/main/default/objects/Contract"
remove_dir "force-app/main/default/objects/ContractContactRole"
remove_dir "force-app/main/default/objects/ContractLineItem"
remove_dir "force-app/main/default/objects/ConversationApiLog"
remove_dir "force-app/main/default/objects/ConversationApiLogObjSum"
remove_dir "force-app/main/default/objects/Coupon"
remove_dir "force-app/main/default/objects/CouponCodeRedemption"
remove_dir "force-app/main/default/objects/CreditMemo"
remove_dir "force-app/main/default/objects/CreditMemoInvApplication"
remove_dir "force-app/main/default/objects/CreditMemoInvApplication"
remove_dir "force-app/main/default/objects/CreditMemoLine"
remove_dir "force-app/main/default/objects/Customer"
remove_dir "force-app/main/default/objects/DandBCompany"
remove_dir "force-app/main/default/objects/DataAction"
remove_dir "force-app/main/default/objects/DataActionJobSummary"
remove_dir "force-app/main/default/objects/DataActionTarget"
remove_dir "force-app/main/default/objects/DataCommCapActvTarget"
remove_dir "force-app/main/default/objects/DataCommunicationCap"
remove_dir "force-app/main/default/objects/DataGraph"
remove_dir "force-app/main/default/objects/DataHarmonizedModelObjRef"
remove_dir "force-app/main/default/objects/DataKitDeploymentLog"
remove_dir "force-app/main/default/objects/DataLakeObjectInstance"
remove_dir "force-app/main/default/objects/DataLineageDefSyncLog"
remove_dir "force-app/main/default/objects/DataLineageNodeDefSyncLog"
remove_dir "force-app/main/default/objects/DataMaskCustomValueLibrary"
remove_dir "force-app/main/default/objects/DataModelRelationConstraint"
remove_dir "force-app/main/default/objects/DataPackageKit"
remove_dir "force-app/main/default/objects/DataQueryWorkspace"
remove_dir "force-app/main/default/objects/DataQueryWorkspaceTab"
remove_dir "force-app/main/default/objects/DataSourceBundle"
remove_dir "force-app/main/default/objects/DataStream"
remove_dir "force-app/main/default/objects/DataUseLegalBasis"
remove_dir "force-app/main/default/objects/DataUsePurpose"
remove_dir "force-app/main/default/objects/DeliveryEstimationSetup"
remove_dir "force-app/main/default/objects/DigitalWallet"
remove_dir "force-app/main/default/objects/DuplicateRecordItem"
remove_dir "force-app/main/default/objects/DuplicateRecordSet"
remove_dir "force-app/main/default/objects/EmailMessage"
remove_dir "force-app/main/default/objects/EngagementChannelType"
remove_dir "force-app/main/default/objects/EngagementChannelWorkType"
remove_dir "force-app/main/default/objects/Entitlement"
remove_dir "force-app/main/default/objects/EntitlementContact"
remove_dir "force-app/main/default/objects/EntityMilestone"
remove_dir "force-app/main/default/objects/Event"
remove_dir "force-app/main/default/objects/ExchangeUserMapping"
remove_dir "force-app/main/default/objects/ExpressionFilter"
remove_dir "force-app/main/default/objects/ExpressionFilterCriteria"
remove_dir "force-app/main/default/objects/ExtDataShare"
remove_dir "force-app/main/default/objects/ExtDataShareTarget"
remove_dir "force-app/main/default/objects/ExternalEventMapping"
remove_dir "force-app/main/default/objects/FeedItem"
remove_dir "force-app/main/default/objects/FinanceBalanceSnapshot"
remove_dir "force-app/main/default/objects/FinanceTransaction"
remove_dir "force-app/main/default/objects/FlowOrchestrationInstance"
remove_dir "force-app/main/default/objects/FlowOrchestrationLog"
remove_dir "force-app/main/default/objects/FlowOrchestrationStageInstance"
remove_dir "force-app/main/default/objects/FlowOrchestrationStepInstance"
remove_dir "force-app/main/default/objects/FlowOrchestrationWorkItem"
remove_dir "force-app/main/default/objects/FulfillmentOrder"
remove_dir "force-app/main/default/objects/FulfillmentOrderItemAdjustment"
remove_dir "force-app/main/default/objects/FulfillmentOrderItemTax"
remove_dir "force-app/main/default/objects/FulfillmentOrderLineItem"
remove_dir "force-app/main/default/objects/Idea"
remove_dir "force-app/main/default/objects/IdentityResolution"
remove_dir "force-app/main/default/objects/Image"
remove_dir "force-app/main/default/objects/Incident"
remove_dir "force-app/main/default/objects/IncidentRelatedItem"
remove_dir "force-app/main/default/objects/Individual"
remove_dir "force-app/main/default/objects/InventoryItemReservation"
remove_dir "force-app/main/default/objects/InventoryReservation"
remove_dir "force-app/main/default/objects/Invoice"
remove_dir "force-app/main/default/objects/InvoiceLine"
remove_dir "force-app/main/default/objects/Lead"
remove_dir "force-app/main/default/objects/LeadCleanInfo"
remove_dir "force-app/main/default/objects/LegalEntity"
remove_dir "force-app/main/default/objects/Location"
remove_dir "force-app/main/default/objects/LocationGroup"
remove_dir "force-app/main/default/objects/LocationGroupAssignment"
remove_dir "force-app/main/default/objects/LocationShippingCarrierMethod"
remove_dir "force-app/main/default/objects/Macro"
remove_dir "force-app/main/default/objects/MacroAction"
remove_dir "force-app/main/default/objects/MacroInstruction"
remove_dir "force-app/main/default/objects/MacroUsage"
remove_dir "force-app/main/default/objects/MarketSegment"
remove_dir "force-app/main/default/objects/MarketSegmentActivation"
remove_dir "force-app/main/default/objects/MarketSegmentField"
remove_dir "force-app/main/default/objects/MessagingEndUser"
remove_dir "force-app/main/default/objects/MessagingSession"
remove_dir "force-app/main/default/objects/MktCalculatedInsight"
remove_dir "force-app/main/default/objects/MktDataTransform"
remove_dir "force-app/main/default/objects/MktMLModel"
remove_dir "force-app/main/default/objects/MktMLModelPartitionRun"
remove_dir "force-app/main/default/objects/MktMLPredictionJob"
remove_dir "force-app/main/default/objects/MLModel"
remove_dir "force-app/main/default/objects/MLModelFactor"
remove_dir "force-app/main/default/objects/MLModelFactorComponent"
remove_dir "force-app/main/default/objects/OperatingHours"
remove_dir "force-app/main/default/objects/OperatingHoursHoliday"
remove_dir "force-app/main/default/objects/Opportunity"
remove_dir "force-app/main/default/objects/OpportunityCompetitor"
remove_dir "force-app/main/default/objects/OpportunityContactRole"
remove_dir "force-app/main/default/objects/OpportunityLineItem"
remove_dir "force-app/main/default/objects/OpportunityRelatedDeleteLog"
remove_dir "force-app/main/default/objects/Order"
remove_dir "force-app/main/default/objects/OrderItem"
remove_dir "force-app/main/default/objects/OrgMetricScanResult"
remove_dir "force-app/main/default/objects/OrgMetricScanSummary"
remove_dir "force-app/main/default/objects/PartnerRole"
remove_dir "force-app/main/default/objects/PartyConsent"
remove_dir "force-app/main/default/objects/Payment"
remove_dir "force-app/main/default/objects/PaymentAuthAdjustment"
remove_dir "force-app/main/default/objects/PaymentAuthorization"
remove_dir "force-app/main/default/objects/PaymentGateway"
remove_dir "force-app/main/default/objects/PaymentGroup"
remove_dir "force-app/main/default/objects/PaymentLineInvoice"
remove_dir "force-app/main/default/objects/PaymentMethod"
remove_dir "force-app/main/default/objects/PendingServiceRouting"
remove_dir "force-app/main/default/objects/Pricebook2"
remove_dir "force-app/main/default/objects/PricebookEntry"
remove_dir "force-app/main/default/objects/PrivacyJobSession"
remove_dir "force-app/main/default/objects/PrivacyRTBFRequest"
remove_dir "force-app/main/default/objects/Problem"
remove_dir "force-app/main/default/objects/ProblemIncident"
remove_dir "force-app/main/default/objects/ProblemRelatedItem"
remove_dir "force-app/main/default/objects/ProcessException"
remove_dir "force-app/main/default/objects/Product2"
remove_dir "force-app/main/default/objects/ProductAttribute"
remove_dir "force-app/main/default/objects/ProductAttributeSetProduct"
remove_dir "force-app/main/default/objects/ProductCatalog"
remove_dir "force-app/main/default/objects/ProductCategory"
remove_dir "force-app/main/default/objects/ProductCategoryProduct"
remove_dir "force-app/main/default/objects/ProductConsumptionSchedule"
remove_dir "force-app/main/default/objects/Promotion"
remove_dir "force-app/main/default/objects/PromotionLineItemRule"
remove_dir "force-app/main/default/objects/PromotionMarketSegment"
remove_dir "force-app/main/default/objects/PromotionQualifier"
remove_dir "force-app/main/default/objects/PromotionSegment"
remove_dir "force-app/main/default/objects/PromotionSegmentBuyerGroup"
remove_dir "force-app/main/default/objects/PromotionSegmentSalesStore"
remove_dir "force-app/main/default/objects/PromotionTarget"
remove_dir "force-app/main/default/objects/PromotionTier"
remove_dir "force-app/main/default/objects/PromptAction"
remove_dir "force-app/main/default/objects/PromptError"
remove_dir "force-app/main/default/objects/QuickText"
remove_dir "force-app/main/default/objects/QuickTextUsage"
remove_dir "force-app/main/default/objects/Recommendation"
remove_dir "force-app/main/default/objects/RecordAction"
remove_dir "force-app/main/default/objects/RecordMergeHistory"
remove_dir "force-app/main/default/objects/Refund"
remove_dir "force-app/main/default/objects/RefundLinePayment"
remove_dir "force-app/main/default/objects/ReportAnomalyEventStore"
remove_dir "force-app/main/default/objects/ResourceAbsence"
remove_dir "force-app/main/default/objects/ResourcePreference"
remove_dir "force-app/main/default/objects/ReturnOrder"
remove_dir "force-app/main/default/objects/ReturnOrderItemAdjustment"
remove_dir "force-app/main/default/objects/ReturnOrderItemTax"
remove_dir "force-app/main/default/objects/ReturnOrderLineItem"
remove_dir "force-app/main/default/objects/SalesStore"
remove_dir "force-app/main/default/objects/Scorecard"
remove_dir "force-app/main/default/objects/ScorecardAssociation"
remove_dir "force-app/main/default/objects/ScorecardMetric"
remove_dir "force-app/main/default/objects/Seller"
remove_dir "force-app/main/default/objects/ServiceAppointment"
remove_dir "force-app/main/default/objects/ServiceAppointmentAttendee"
remove_dir "force-app/main/default/objects/ServiceContract"
remove_dir "force-app/main/default/objects/ServiceResource"
remove_dir "force-app/main/default/objects/ServiceResourceSkill"
remove_dir "force-app/main/default/objects/ServiceTerritory"
remove_dir "force-app/main/default/objects/ServiceTerritoryMember"
remove_dir "force-app/main/default/objects/ServiceTerritoryWorkType"
remove_dir "force-app/main/default/objects/Shift"
remove_dir "force-app/main/default/objects/ShiftEngagementChannel"
remove_dir "force-app/main/default/objects/ShiftWorkTopic"
remove_dir "force-app/main/default/objects/Shipment"
remove_dir "force-app/main/default/objects/ShipmentItem"
remove_dir "force-app/main/default/objects/ShippingCarrier"
remove_dir "force-app/main/default/objects/ShippingCarrierMethod"
remove_dir "force-app/main/default/objects/ShippingConfigurationSet"
remove_dir "force-app/main/default/objects/ShippingRateArea"
remove_dir "force-app/main/default/objects/ShippingRateGroup"
remove_dir "force-app/main/default/objects/Site"
remove_dir "force-app/main/default/objects/SkillRequirement"
remove_dir "force-app/main/default/objects/SocialPersona"
remove_dir "force-app/main/default/objects/Solution"
remove_dir "force-app/main/default/objects/StandardShippingRate"
remove_dir "force-app/main/default/objects/StreamActivityAccess"
remove_dir "force-app/main/default/objects/StreamingChannel"
remove_dir "force-app/main/default/objects/TableauHostMapping"
remove_dir "force-app/main/default/objects/Task"
remove_dir "force-app/main/default/objects/TimeSlot"
remove_dir "force-app/main/default/objects/Topic"
remove_dir "force-app/main/default/objects/TopicAssignment"
remove_dir "force-app/main/default/objects/UserCapabilityPreference"
remove_dir "force-app/main/default/objects/UserExternalCredential"
remove_dir "force-app/main/default/objects/UserLocalWebServerIdentity"
remove_dir "force-app/main/default/objects/UserPrioritizedRecord"
remove_dir "force-app/main/default/objects/UserProvisioningRequest"
remove_dir "force-app/main/default/objects/UserServicePresence"
remove_dir "force-app/main/default/objects/VoiceCall"
remove_dir "force-app/main/default/objects/Waitlist"
remove_dir "force-app/main/default/objects/WaitlistParticipant"
remove_dir "force-app/main/default/objects/WaitlistServiceResource"
remove_dir "force-app/main/default/objects/WaitlistWorkType"
remove_dir "force-app/main/default/objects/WebCart"
remove_dir "force-app/main/default/objects/WebCartAdjustmentBasis"
remove_dir "force-app/main/default/objects/WebCartAdjustmentGroup"
remove_dir "force-app/main/default/objects/WebCartCredit"
remove_dir "force-app/main/default/objects/WebStore"
remove_dir "force-app/main/default/objects/WebStoreBuyerGroup"
remove_dir "force-app/main/default/objects/WebStoreCatalog"
remove_dir "force-app/main/default/objects/WebStoreInventorySource"
remove_dir "force-app/main/default/objects/WorkOrder"
remove_dir "force-app/main/default/objects/WorkOrderLineItem"
remove_dir "force-app/main/default/objects/WorkPlan"
remove_dir "force-app/main/default/objects/WorkPlanTemplate"
remove_dir "force-app/main/default/objects/WorkPlanTemplateEntry"
remove_dir "force-app/main/default/objects/WorkStep"
remove_dir "force-app/main/default/objects/WorkStepTemplate"
remove_dir "force-app/main/default/objects/WorkType"
remove_dir "force-app/main/default/objects/WorkTypeGroup"
remove_dir "force-app/main/default/objects/WorkTypeGroupMember"

# Remove unnecessary other metadata directories
remove_dir "force-app/main/default/permissionsetgroups"
remove_dir "force-app/main/default/permissionsets"
remove_dir "force-app/main/default/presenceUserConfigs"
remove_dir "force-app/main/default/profilePasswordPolicies"
remove_dir "force-app/main/default/profileSessionSettings"
remove_dir "force-app/main/default/profiles"
remove_dir "force-app/main/default/quickActions"
remove_dir "force-app/main/default/reports"
remove_dir "force-app/main/default/reportTypes"
remove_dir "force-app/main/default/roles"
remove_dir "force-app/main/default/serviceChannels"
remove_dir "force-app/main/default/settings"
remove_dir "force-app/main/default/sharingRules"
remove_dir "force-app/main/default/standardValueSets"
remove_dir "force-app/main/default/standardValueSetTranslations"
remove_dir "force-app/main/default/staticresources"
remove_dir "force-app/main/default/tabs"
remove_dir "force-app/main/default/topicsForObjects"
remove_dir "force-app/main/default/translations"
remove_dir "force-app/main/default/triggers"
remove_dir "force-app/main/default/workflows"

echo ""
echo "✅ Cleanup completed!"
echo ""
echo "📊 Project size after cleanup:"
du -sh force-app/main/default

echo ""
echo "📁 Remaining files:"
find force-app/main/default -name "*.xml" | wc -l

echo ""
echo "📋 Files kept (essential for bill sharing app):"
echo "✅ Custom Objects: Expense__c, ExpenseCategory__c, UserException__c, UserExpense__c"
echo "✅ Custom Tabs: 4 tabs for custom objects"
echo "✅ Custom Field: Contact.MonthlyIncome__c"
echo "✅ Custom Record Type: Account.Household"
echo "✅ Standard Objects: Account, Contact, User (for lookups)"
echo "✅ Essential Profiles: Admin, Standard"
echo "✅ Essential Settings: Security, Sharing, Org"
echo "✅ Sharing Rules: For custom objects"

echo ""
echo "📝 Cleanup log saved to: $LOG_FILE"
echo "🎉 Project cleanup completed successfully!"
